load("@io_bazel_rules_docker//java:image.bzl", "java_image")

java_image(
    name = "java_app",
    srcs = [
    	"image_data/Greeting.java",
    	"image_data/ProjectRunner.java",
    ],
    main_class = "ProjectRunner",
)
